INFO 2024-10-02 12:42:22,487 autoreload 19220 31600 Watching for file changes with StatReloader
INFO 2024-10-02 12:42:46,063 autoreload 19220 31600 C:\Users\Nurzhan\PycharmProjects\gb_django_final\gb_django_final\settings.py changed, reloading.
INFO 2024-10-02 12:42:46,438 autoreload 25824 32460 Watching for file changes with StatReloader
INFO 2024-10-02 12:43:15,104 autoreload 27352 4056 Watching for file changes with StatReloader
ERROR 2024-10-02 12:43:25,010 log 27352 11616 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:25,034 basehttp 27352 11616 "GET / HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:28,630 log 27352 11616 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:28,631 basehttp 27352 11616 "GET / HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:29,398 log 27352 11616 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:29,400 basehttp 27352 11616 "GET / HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:34,154 log 27352 11616 Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:34,156 basehttp 27352 11616 "GET /login/ HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:34,959 log 27352 11616 Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:34,961 basehttp 27352 11616 "GET /login/ HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:35,348 log 27352 11616 Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:35,351 basehttp 27352 11616 "GET /login/ HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:36,393 log 27352 11616 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:36,395 basehttp 27352 11616 "GET / HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:37,085 log 27352 11616 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:37,087 basehttp 27352 11616 "GET / HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:37,284 log 27352 11616 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:37,286 basehttp 27352 11616 "GET / HTTP/1.1" 500 1565
ERROR 2024-10-02 12:43:40,138 log 27352 11616 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nurzhan\PycharmProjects\gb_django_final\.venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-10-02 12:43:40,140 basehttp 27352 11616 "GET / HTTP/1.1" 500 1565
INFO 2024-10-02 12:44:53,907 autoreload 27352 4056 C:\Users\Nurzhan\PycharmProjects\gb_django_final\gb_django_final\settings.py changed, reloading.
INFO 2024-10-02 12:44:54,282 autoreload 18928 21548 Watching for file changes with StatReloader
INFO 2024-10-02 12:45:37,977 autoreload 17580 2720 Watching for file changes with StatReloader
WARNING 2024-10-02 12:45:39,483 base 17580 28240 Session data corrupted
INFO 2024-10-02 12:45:39,493 basehttp 17580 28240 "GET / HTTP/1.1" 302 0
WARNING 2024-10-02 12:45:39,538 base 17580 28240 Session data corrupted
INFO 2024-10-02 12:45:39,543 basehttp 17580 28240 "GET /login/?next=/ HTTP/1.1" 200 2086
WARNING 2024-10-02 12:45:42,322 base 17580 28240 Session data corrupted
INFO 2024-10-02 12:45:42,333 basehttp 17580 28240 "POST /login/?next=/ HTTP/1.1" 302 0
INFO 2024-10-02 12:45:42,341 basehttp 17580 28240 "GET / HTTP/1.1" 200 4426
WARNING 2024-10-02 12:45:42,392 log 17580 28240 Not Found: /media/recipe_images/salad.jpg
WARNING 2024-10-02 12:45:42,393 log 17580 17036 Not Found: /media/recipe_images/sauce_tDG5021.jpg
WARNING 2024-10-02 12:45:42,393 basehttp 17580 28240 "GET /media/recipe_images/salad.jpg HTTP/1.1" 404 1692
WARNING 2024-10-02 12:45:42,393 basehttp 17580 17036 "GET /media/recipe_images/sauce_tDG5021.jpg HTTP/1.1" 404 1692
INFO 2024-10-02 12:45:48,398 basehttp 17580 17036 "GET /recipes/ HTTP/1.1" 200 5003
INFO 2024-10-02 12:48:06,686 basehttp 17580 17036 "GET / HTTP/1.1" 200 4179
WARNING 2024-10-02 12:48:06,765 log 17580 17036 Not Found: /media/recipe_images/sauce_tDG5021.jpg
WARNING 2024-10-02 12:48:06,766 basehttp 17580 17036 "GET /media/recipe_images/sauce_tDG5021.jpg HTTP/1.1" 404 1692
INFO 2024-10-02 12:48:59,394 basehttp 17580 17036 "GET /recipes/14/ HTTP/1.1" 200 2707
INFO 2024-10-02 12:49:03,450 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2783
WARNING 2024-10-02 12:49:03,508 log 17580 17036 Not Found: /media/recipe_images/sauce_tDG5021.jpg
WARNING 2024-10-02 12:49:03,508 basehttp 17580 17036 "GET /media/recipe_images/sauce_tDG5021.jpg HTTP/1.1" 404 1692
INFO 2024-10-02 12:49:08,501 basehttp 17580 17036 "GET /recipes/ HTTP/1.1" 200 5003
INFO 2024-10-02 12:49:12,237 basehttp 17580 17036 "GET /recipes/9/update/ HTTP/1.1" 302 0
WARNING 2024-10-02 12:49:12,245 log 17580 17036 Forbidden: /wrong_user_error/
WARNING 2024-10-02 12:49:12,246 basehttp 17580 17036 "GET /wrong_user_error/ HTTP/1.1" 403 1694
INFO 2024-10-02 12:49:15,545 basehttp 17580 17036 "GET /logout/ HTTP/1.1" 302 0
INFO 2024-10-02 12:49:15,550 basehttp 17580 17036 "GET / HTTP/1.1" 302 0
INFO 2024-10-02 12:49:15,554 basehttp 17580 17036 "GET /login/?next=/ HTTP/1.1" 200 2086
INFO 2024-10-02 12:49:30,604 basehttp 17580 17036 "POST /login/?next=/ HTTP/1.1" 302 0
INFO 2024-10-02 12:49:30,610 basehttp 17580 17036 "GET / HTTP/1.1" 200 3993
INFO 2024-10-02 12:49:43,008 basehttp 17580 17036 "GET /recipes/ HTTP/1.1" 200 5001
INFO 2024-10-02 12:49:46,355 basehttp 17580 17036 "GET /recipes/9/update/ HTTP/1.1" 200 5379
INFO 2024-10-02 12:50:12,747 basehttp 17580 17036 "POST /recipes/9/update/ HTTP/1.1" 302 0
INFO 2024-10-02 12:50:12,755 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2763
WARNING 2024-10-02 12:50:12,792 log 17580 17036 Not Found: /media/recipe_images/sauce_ywUrkAS.jpg
WARNING 2024-10-02 12:50:12,792 basehttp 17580 17036 "GET /media/recipe_images/sauce_ywUrkAS.jpg HTTP/1.1" 404 1690
INFO 2024-10-02 12:50:16,073 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2763
WARNING 2024-10-02 12:50:16,122 log 17580 17036 Not Found: /media/recipe_images/sauce_ywUrkAS.jpg
WARNING 2024-10-02 12:50:16,122 basehttp 17580 17036 "GET /media/recipe_images/sauce_ywUrkAS.jpg HTTP/1.1" 404 1690
INFO 2024-10-02 12:50:16,569 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2763
WARNING 2024-10-02 12:50:16,605 log 17580 17036 Not Found: /media/recipe_images/sauce_ywUrkAS.jpg
WARNING 2024-10-02 12:50:16,605 basehttp 17580 17036 "GET /media/recipe_images/sauce_ywUrkAS.jpg HTTP/1.1" 404 1690
INFO 2024-10-02 12:50:16,755 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2763
WARNING 2024-10-02 12:50:16,787 log 17580 17036 Not Found: /media/recipe_images/sauce_ywUrkAS.jpg
WARNING 2024-10-02 12:50:16,787 basehttp 17580 17036 "GET /media/recipe_images/sauce_ywUrkAS.jpg HTTP/1.1" 404 1690
INFO 2024-10-02 12:50:16,932 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2763
WARNING 2024-10-02 12:50:16,962 log 17580 17036 Not Found: /media/recipe_images/sauce_ywUrkAS.jpg
WARNING 2024-10-02 12:50:16,963 basehttp 17580 17036 "GET /media/recipe_images/sauce_ywUrkAS.jpg HTTP/1.1" 404 1690
INFO 2024-10-02 12:50:17,092 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2763
WARNING 2024-10-02 12:50:17,129 log 17580 17036 Not Found: /media/recipe_images/sauce_ywUrkAS.jpg
WARNING 2024-10-02 12:50:17,129 basehttp 17580 17036 "GET /media/recipe_images/sauce_ywUrkAS.jpg HTTP/1.1" 404 1690
INFO 2024-10-02 12:51:20,920 basehttp 17580 17036 "GET /recipes/9/update/ HTTP/1.1" 200 5388
INFO 2024-10-02 12:51:33,154 basehttp 17580 17036 "POST /recipes/9/update/ HTTP/1.1" 200 5526
INFO 2024-10-02 12:51:46,294 basehttp 17580 17036 "POST /recipes/9/update/ HTTP/1.1" 302 0
INFO 2024-10-02 12:51:46,304 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2763
WARNING 2024-10-02 12:51:46,358 log 17580 17036 Not Found: /media/recipe_images/sauce_LWVxhhW.jpg
WARNING 2024-10-02 12:51:46,359 basehttp 17580 17036 "GET /media/recipe_images/sauce_LWVxhhW.jpg HTTP/1.1" 404 1690
INFO 2024-10-02 12:51:50,281 basehttp 17580 17036 "GET /recipes/9/update/ HTTP/1.1" 200 5388
INFO 2024-10-02 12:51:53,147 basehttp 17580 17036 "POST /recipes/9/update/ HTTP/1.1" 200 5526
INFO 2024-10-02 12:52:01,251 basehttp 17580 17036 "POST /recipes/9/update/ HTTP/1.1" 302 0
INFO 2024-10-02 12:52:01,259 basehttp 17580 17036 "GET /recipes/9/ HTTP/1.1" 200 2730
INFO 2024-10-02 12:52:32,328 basehttp 17580 17036 "GET / HTTP/1.1" 200 4068
INFO 2024-10-02 12:52:35,234 basehttp 17580 17036 "GET /logout/ HTTP/1.1" 302 0
INFO 2024-10-02 12:52:35,239 basehttp 17580 17036 "GET / HTTP/1.1" 302 0
INFO 2024-10-02 12:52:35,246 basehttp 17580 17036 "GET /login/?next=/ HTTP/1.1" 200 2086
